apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
  creationTimestamp: null
  name: codefresh
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: codefresh project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: codefresh
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/**/codefresh/config.json
        repoURL: https://github.com/noam-codefresh/demo.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argo-autopilot
        app.kubernetes.io/name: "{{ appName }}"
      name: codefresh-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: "{{ destNamespace }}"
        server: "{{ destServer }}"
      project: codefresh
      source:
        path: "{{ srcPath }}"
        repoURL: "{{ srcRepoURL }}"
        targetRevision: "{{ srcTargetRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
status: {}
