apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: components-reporter
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  
  # actual state
  resource:
    components:
      # resource group
      group: '*'
      # resource version
      version: '*'
      # resource kind
      resource: '*'

      filter:
        afterStart: true
        labels:
          - key: "codefresh.io/component"
            operation: "=="
            value: "true"
