
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: components-reporter
spec:

  dependencies:
    - name: components-reporter
      eventSourceName: components-reporter
      eventName: components

  triggers:    
    - template:
        conditions: components-reporter # only run when actual event happens
        name: http-trigger
        http:
          url: <codefresh-url> # send event directly to codefresh?
          payload:
            - src:
                dependencyName: actual
                dataKey: body
              dest: payload
          method: POST
          headers:
            Content-Type: application/json
            X-Access-Token: <codefresh-api-key>
      retryStrategy:
        steps: 3
        duration: 3s