apiVersion: v1
kind: ConfigMap
metadata:                                                                                                                                        
  name: project1
  label:
    codefresh.io/project: project1
data: {}