apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  name: components-reporter
  namespace: codefresh
spec:
  eventBusName: codefresh-eventbus
  resource:
    components:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
        labels:
        - key: codefresh.io/component
          operation: '!='
          value: ""
      group: argoproj.io
      namespace: codefresh
      resource: applications
      version: v1alpha1
    runtime:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        afterStart: true
        createdBy: null
        labels:
        - key: codefresh.io/component
          operation: '!='
          value: ""
      group: argoproj.io
      namespace: codefresh
      resource: applicationsets
      version: v1alpha1
  service:
    ports:
    - port: 12000
      targetPort: 12000
  template:
    serviceAccountName: components-reporter-sa
status: {}
