apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argo-autopilot
    app.kubernetes.io/name: git-source-1-synchronizer
  name: git-source-1-synchronizer
  namespace: codefresh
spec:
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: codefresh
  source:
    path: manifests
    repoURL: https://github.com/roi-codefresh/git-source1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true